Allows to sho doc-test stdout with `test --debug`

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
+# SPDX-FileCopyrightText: 2021 - 2023 Robin Vobruba <hoijui.quaero@gmail.com>
 #
 # SPDX-License-Identifier: Unlicense
 
@@ -9,10 +9,50 @@
 set -Eeuo pipefail
 #set -Eeu
 
-#script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
-#source "$script_dir/env"
+# initial default values
+APP_NAME="Rust project test script"
+debug=false
 
-# We run all tests, even if some are failing.
+function print_help() {
+
+	local script_name="$(basename "$0")"
+	echo "$APP_NAME -"
+	echo "We run all tests, even if some are failing."
+	echo
+	echo "Usage:"
+	echo "  $script_name [OPTION...]"
+	echo "Options:"
+	echo "  -h, --help"
+	echo "    Show this help message and exit"
+	echo "  -d, --debug"
+	echo "    Shows stdout for doc-test (and maybe more in the future)"
+	echo "Examples:"
+	echo "  $script_name"
+	echo "  $script_name --debug"
+}
+
+# read command-line args
+POSITIONAL=()
+while [[ $# -gt 0 ]]
+do
+	arg="$1"
+	shift # $2 -> $1, $3 -> $2, ...
+
+	case "$arg" in
+		-h|--help)
+			print_help
+			exit 0
+			;;
+		-d|--debug)
+			debug=true
+			;;
+		*) # non-/unknown option
+			POSITIONAL+=("$arg") # save it in an array for later
+			;;
+	esac
+done
+set -- "${POSITIONAL[@]}" # restore positional parameters
+
 
 tests=0
 failures=0
@@ -78,7 +118,12 @@ echo "TEST: 'cargo doc-code(-tests)' - Building documentaiton and running docu c
 # For more, see the chapter on documentation tests:
 # https://doc.rust-lang.org/rustdoc/documentation-tests.html
 failed=0
-cargo test --release --doc || failed=1
+if $debug
+then
+  cargo test --release --doc -- --show-output || failed=1
+else
+  cargo test --release --doc || failed=1
+fi
 failures=$((failures + failed))
 tests=$((tests + 1))
 _report_test_res "$failed"
