test: Unifies indents [minor]

diff --git a/test b/test
--- a/test
+++ b/test
@@ -54,21 +54,20 @@ do
 done
 set -- "${POSITIONAL[@]}" # restore positional parameters
 
-
 tests=0
 failures=0
 failed_tests=()
 
 function _report_test_res() {
-  res="$1"
-  t_human_id="$2"
-  echo -n "TEST: $t_human_id: "
-  if [ "$res" -eq 0 ]
-  then
-    echo "succeeded."
-  else
-    echo "failed."
-  fi
+	res="$1"
+	t_human_id="$2"
+	echo -n "TEST: $t_human_id: "
+	if [ "$res" -eq 0 ]
+	then
+		echo "succeeded."
+	else
+		echo "failed."
+	fi
 }
 
 echo
@@ -124,7 +123,7 @@ t_human_id="'cargo clippy' - Static code linting"
 echo "TEST: $t_human_id"
 failed=0
 cargo clippy --release -- \
-  || failed=1
+	|| failed=1
 failures=$((failures + failed))
 tests=$((tests + 1))
 _report_test_res "$failed" "$t_human_id"
@@ -143,16 +142,16 @@ echo "TEST: $t_human_id"
 failed=0
 if [ -f "src/lib.rs" ]
 then
-  # This only tests the library, but fails if the project is/has no library
-  doc_target="--doc"
+	# This only tests the library, but fails if the project is/has no library
+	doc_target="--doc"
 else
-  doc_target="--all-targets"
+	doc_target="--all-targets"
 fi
 if $debug
 then
-  cargo test --release $doc_target -- --show-output || failed=1
+	cargo test --release $doc_target -- --show-output || failed=1
 else
-  cargo test --release $doc_target || failed=1
+	cargo test --release $doc_target || failed=1
 fi
 failures=$((failures + failed))
 tests=$((tests + 1))
@@ -168,17 +167,17 @@ t_human_id="'REUSE' - Licensing meta-data check"
 echo "TEST: $t_human_id"
 if which reuse > /dev/null
 then
-  failed=0
-  reuse lint || failed=1
-  failures=$((failures + failed))
-  tests=$((tests + 1))
-  _report_test_res "$failed" "$t_human_id"
+	failed=0
+	reuse lint || failed=1
+	failures=$((failures + failed))
+	tests=$((tests + 1))
+	_report_test_res "$failed" "$t_human_id"
 	if [ "$failed" = "1" ]
 	then
 		failed_tests+=("$t_human_id")
 	fi
-else
-  >&2 echo "WARNING: REUSE tool not found; skipping licensing meta-data check."
+	else
+	>&2 echo "WARNING: REUSE tool not found; skipping licensing meta-data check."
 fi
 
 echo
@@ -186,15 +185,15 @@ echo
 echo "Successful tests: $((tests - failures))/$tests"
 if [ $failures -eq 0 ]
 then
-  echo "All tests successfull!"
+	echo "All tests successfull!"
 else
-  {
+	{
 	echo "There were $failures test failures:"
 	for failed_test_id in "${failed_tests[@]}"
 	do
 		echo "- $failed_test_id"
 	done
-  } >&2
+	} >&2
 fi
 
 exit $failures
